
version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      REDIS_URL: redis://redis:6379
      AWS_REGION: "us-east-1"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE: "http://localhost:3001"
