
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-backend
  template:
    metadata:
      labels:
        app: content-backend
    spec:
      containers:
        - name: backend
          image: yourrepo/content-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: content-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
